FROM node:22-alpine3.23 as base

WORKDIR /app

RUN apk add --no-cache make

COPY Makefile .
COPY web ./web

FROM base as build

RUN make build-web

FROM base as test

RUN make test-web

FROM nginx:1.21.6-alpine as final

COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/web/dist /usr/share/nginx/html